### PR TITLE
Create pasu.yml

### PR DESCRIPTION
**Pull request by pasumps1**

### CODE REVIEW

**Comment by afewell** [comment]
Hi @pasumps1 sorry for not seeing this sooner, it looks like your member page does not show that you completed enrollment for this course. Sorry I know some of the instructions could still use improvement. While registration for the community only needs to be one time, you will need to do a course enrollment step for every course, as each time you enroll in a course, it runs a github action workflow that prepares your member page to hold your records for that course. 

The steps to enroll in a course are exactly the same as the steps you took to request the certificate of completion, you just post a file named yourgithubusername.yml to a directory, the only difference is to enroll, you will post this file to the registered_members directory instead of the certs_awarded directory and when you do that it should automatically process your course enrollment and then you can submit tests and request your certificate of completion. Please let me know if you have any problems with the course enrollment. Thanks!

**Comment by pasumps1** [comment]
Hi ,

As per your request I have successfully registered anc configured

I still facing to get the completion certificate

Please do the needful

**Comment by afewell** [comment]
Hi @pasumps1 I can see that you enrolled and completed the vSphere with Tanzu 101 course, but I cannot find any record of your enrollment for the ModernApps Skills 101 course, the github actions tab on this site shows all workflow runs and the pullrequests tabs shows a record of all pullrequests, and I do not see any record. 

If you complete the enrollment process for the ModernApps Skills 101 course as shown here: [https://modernapps.ninja/modernappsskills101_ms4043/docs/courseenrollment/](https://modernapps.ninja/modernappsskills101_ms4043/docs/courseenrollment/), then submit or resubmit the required test, and then resubmit the course completion request, that should correct the issue. Thanks!

**Comment by pasumps1** [comment]
Hi ,

I just completed ModernApps Skills 101 course and followed the procedure as
per document given in the link

Regards,

Pasumpon S

**Comment by pasumps1** [comment]
Hi

when i try to get the completion certificate i am getting error - 404 like
that

https://github.com/modernappsninjas/pasumps1/blob/main/content/english/certs/null

regards,

pasumpon

**Comment by afewell** [comment]
hi @pasumps1 it looks like it was not able to provision your badge because there is no information in your member record so it has nothing to assign the badge to ... at minimum I need to have an email address, it does not matter if its a free email account like gmail or something as long as its a valid email. 

If you can provide at least your preferred email address or any additional information you would like to share, I can manually update your member and course records and badge:

preferredEmailAddress: ""  
firstName: ""  
lastName: ""  
twitterUsername: ""  
linkedinUsername: ""  
isVmwareEmployee: false  
vmwareEmailAddress: ""

Thanks!

**Comment by afewell** [comment]
@pasumps1 oh sorry nevermind I just found your member record info, it looks like it didnt process correctly because the values would normally go inside the quotation marks, my apologies I know the instructions still need work to be more clear. 

I will get everything fixed up and get your badge provisioned, it may take me a day or so but I will get this fixed for you. Thanks for your patience and for participating in the program!

**Comment by pasumps1** [comment]
Hi ,

I hope the issue will be resolved soon to get the completion certificate

Kindly do the needful

Regards,

Pasumpon S

**Pull request closed without merging**
